require 'mechanize'
require "rest_client"
require 'pry-nav'
require 'nokogiri'
require 'csv'

class Scraper 
	attr_reader :rows, :ids, :noko
	def initialize
		@rows = []
	end

	def get_ocd_ids
		page = RestClient.get("https://raw.githubusercontent.com/opencivicdata/ocd-division-ids/master/identifiers/country-us/census_autogenerated/us_census_places.csv")
		noko = Nokogiri::HTML(page)
		@ids = noko.text.lines.select do |line|
			line =~ /state:md/
		end.reject do |line|
			line =~ /place:/
		end.map do |line|
		  line.gsub(/,.+/, '').gsub(/\n/, '')
		end 
	end 

	def fetch_page
		page = RestClient.get("http://www.elections.state.md.us/about/county_boards.html")
		@noko = Nokogiri::HTML(page) 
	end

	def iterate_through_page
		i = 0
		while i < 23 do 
			jurisdiction_name = noko.css('.mdgov_contentWrapper').css('p')[i].element_children[0].text
			office = jurisdiction_name + " Elections"
			phone = noko.css('.mdgov_contentWrapper').css('p')[i].text.scan(/\d{3}-\d{3}-\d{4}/).first
			website = noko.css('.mdgov_contentWrapper').css('p')[i].elements.select { |el| el.attribute('href') }.first.text
			id = @ids.find do |i| 
				name = jurisdiction_name.rstrip.gsub(" County", "").gsub(" ", "_").gsub("'","~").gsub(".","")
				i =~ /county:#{name}/i
			end || ""
			i += 1
			@rows << [jurisdiction_name, "Maryland", office, phone, website, id]	
		end


	end			

	def write_into_CSV_file
		CSV.open("spreadsheet.csv", "wb") do |csv|
			@rows.map do |line|
				csv << line
			end
		end
	end

end

a = Scraper.new
a.get_ocd_ids
a.fetch_page
a.iterate_through_page
a.write_into_CSV_file
